import { AnalysisResult, Crop, RecentSurvey } from "./types";
import { THAILAND_SOIL_GROUPS } from "./soil-groups-thailand";

export const mockRecentSurveys: RecentSurvey[] = [
  {
    id: "survey-suphan-1",
    name: "แปลงสวนผสม สุพรรณบุรี",
    subdistrict: "ต.ศรีประจันต์ อ.ศรีประจันต์ จ.สุพรรณบุรี",
    lat: 14.62,
    lng: 100.14,
    coords_formatted: "14.62° N, 100.14° E",
    area_rai: 45.2,
    area_ha: 7.23,
    status: "ACTIVE",
    polygon: [
      [14.625, 100.135],
      [14.627, 100.146],
      [14.616, 100.148],
      [14.614, 100.136],
    ],
  },
  {
    id: "survey-danchang-2",
    name: "นาข้าวอินทรีย์ ด่านช้าง",
    subdistrict: "ต.หนองหญ้าไซ อ.ด่านช้าง จ.สุพรรณบุรี",
    lat: 14.84,
    lng: 99.71,
    coords_formatted: "14.84° N, 99.71° E",
    area_rai: 128.5,
    area_ha: 20.56,
    status: "ACTIVE",
    polygon: [
      [14.845, 99.705],
      [14.847, 99.716],
      [14.836, 99.718],
      [14.834, 99.706],
    ],
  },
  {
    id: "survey-nakhonpathom-3",
    name: "ไร่อ้อย นครปฐม",
    subdistrict: "ต.ทุ่งบัว อ.กำแพงแสน จ.นครปฐม",
    lat: 13.92,
    lng: 100.04,
    coords_formatted: "13.92° N, 100.04° E",
    area_rai: 62.1,
    area_ha: 9.94,
    status: "ACTIVE",
    polygon: [
      [13.925, 100.035],
      [13.927, 100.046],
      [13.916, 100.048],
      [13.914, 100.036],
    ],
  },
];

export const mockAnalysisResults: Record<string, AnalysisResult> = {
  "survey-suphan-1": {
    id: "survey-suphan-1",
    location_name: "แปลงสวนผสม สุพรรณบุรี (อ.ศรีประจันต์)",
    coordinates: {
      lat: 14.62,
      lng: 100.14,
      formatted: "LAT: 14.6200° N, LON: 100.1400° E",
    },
    area_size: {
      rai: 45.2,
      ha: 7.23,
      sqm: 72320,
    },
    analyzed_date: "31 สิงหาคม 2026",
    overall_land_suitability: {
      indexScore: 0.88,
      indexPercentage: 88,
      fao_class: "S1",
      fao_label: "เหมาะสมมาก (S1)",
      ahp_weights: { slope: 0.251, soil_ph: 0.166, rainfall: 0.098, temperature: 0.054, land_use: 0.098, irrigation: 0.141, ndvi: 0.098, soil_moisture: 0.094 },
      consistency_ratio: 0.0216,
      cr_passed: true,
      normalized_criteria: { slope_norm: 1.0, ph_norm: 1.0, rainfall_norm: 0.85, temp_norm: 1.0, land_use_norm: 1.0, irrigation_norm: 0.90, ndvi_norm: 0.88, moisture_norm: 0.85 },
      summary_th: "ค่าความเหมาะสมต่อการเกษตรโดยรวม: 0.88 (S1) — คำนวณตามสูตร AHP Weighted Overlay 8 ปัจจัย S = Σ(wi × xi) (CR = 0.0216 < 0.10)",
    },
    suitability_score: 88,
    status_label: "เหมาะสมมาก",
    status_color: "#6B8E5A",
    fao_class: "S1",
    fao_label: "เหมาะสมมาก (S1)",
    ndvi_value: 0.74,
    ndvi_trend: [
      { month: "มี.ค.", value: 0.62 },
      { month: "เม.ย.", value: 0.58 },
      { month: "พ.ค.", value: 0.69 },
      { month: "มิ.ย.", value: 0.72 },
      { month: "ก.ค.", value: 0.76 },
      { month: "ส.ค.", value: 0.74 },
    ],
    soil_moisture: 68,
    slope_degrees: 1.8,
    elevation_amsl: 12.4,
    surface_temp: 29.5,
    rainfall_mm: 1240,
    soil_ph: 6.2,
    land_use_class: "Cropland",
    soil_group: THAILAND_SOIL_GROUPS[7],
    insight_text:
      "ผืนดินแปลงนี้จัดอยู่ในชั้นความเหมาะสมสูง (FAO Class S1) มีความอุดมสมบูรณ์สูง ตรวจพบคุณสมบัติกลุ่มชุดดินที่ 7 (ดินเหนียวที่ราบลุ่มน้ำจืด) มีค่าดัชนีพืชพรรณ (NDVI) สม่ำเสมอที่ 0.74 และระดับความชื้นในดินเฉลี่ย 68% มีความลาดชันต่ำเพียง 1.8 องศา ระบายน้ำได้ดีเยี่ยม เหมาะอย่างยิ่งสำหรับการทำเกษตรผสมผสาน พืชสวน และนาข้าวคุณภาพสูง",
  },
  "survey-danchang-2": {
    id: "survey-danchang-2",
    location_name: "นาข้าวอินทรีย์ ด่านช้าง จ.สุพรรณบุรี",
    coordinates: {
      lat: 14.84,
      lng: 99.71,
      formatted: "LAT: 14.8400° N, LON: 99.7100° E",
    },
    area_size: {
      rai: 128.5,
      ha: 20.56,
      sqm: 205600,
    },
    analyzed_date: "29 สิงหาคม 2026",
    overall_land_suitability: {
      indexScore: 0.82,
      indexPercentage: 82,
      fao_class: "S2",
      fao_label: "เหมาะสมปานกลาง (S2)",
      ahp_weights: { slope: 0.251, soil_ph: 0.166, rainfall: 0.098, temperature: 0.054, land_use: 0.098, irrigation: 0.141, ndvi: 0.098, soil_moisture: 0.094 },
      consistency_ratio: 0.0216,
      cr_passed: true,
      normalized_criteria: { slope_norm: 0.85, ph_norm: 1.0, rainfall_norm: 0.85, temp_norm: 1.0, land_use_norm: 1.0, irrigation_norm: 0.85, ndvi_norm: 0.80, moisture_norm: 1.0 },
      summary_th: "ค่าความเหมาะสมต่อการเกษตรโดยรวม: 0.82 (S2) — คำนวณตามสูตร AHP Weighted Overlay 8 ปัจจัย S = Σ(wi × xi) (CR = 0.0216 < 0.10)",
    },
    suitability_score: 82,
    status_label: "เหมาะสมมาก",
    status_color: "#6B8E5A",
    fao_class: "S2",
    fao_label: "เหมาะสมปานกลาง (S2)",
    ndvi_value: 0.68,
    ndvi_trend: [
      { month: "มี.ค.", value: 0.51 },
      { month: "เม.ย.", value: 0.48 },
      { month: "พ.ค.", value: 0.64 },
      { month: "มิ.ย.", value: 0.67 },
      { month: "ก.ค.", value: 0.71 },
      { month: "ส.ค.", value: 0.68 },
    ],
    soil_moisture: 72,
    slope_degrees: 2.1,
    elevation_amsl: 45.0,
    surface_temp: 28.2,
    rainfall_mm: 1310,
    soil_ph: 6.2,
    land_use_class: "Cropland",
    soil_group: THAILAND_SOIL_GROUPS[7],
    insight_text:
      "แปลงดินมีชั้นดินเหนียวปนร่วนที่อุ้มน้ำได้ดีมาก ดัชนีความเขียวขจีอยู่ในเกณฑ์ดี มีแหล่งน้ำธรรมชาติใกล้เคียง เหมาะอย่างยิ่งสำหรับการทำนาข้าวอินทรีย์และพืชตระกูลถั่วหมุนเวียน",
  },
  "survey-nakhonpathom-3": {
    id: "survey-nakhonpathom-3",
    location_name: "ไร่อ้อย นครปฐม (อ.กำแพงแสน)",
    coordinates: {
      lat: 13.92,
      lng: 100.04,
      formatted: "LAT: 13.9200° N, LON: 100.0400° E",
    },
    area_size: {
      rai: 62.1,
      ha: 9.94,
      sqm: 99360,
    },
    analyzed_date: "28 สิงหาคม 2026",
    overall_land_suitability: {
      indexScore: 0.79,
      indexPercentage: 79,
      fao_class: "S2",
      fao_label: "เหมาะสมปานกลาง (S2)",
      ahp_weights: { slope: 0.251, soil_ph: 0.166, rainfall: 0.098, temperature: 0.054, land_use: 0.098, irrigation: 0.141, ndvi: 0.098, soil_moisture: 0.094 },
      consistency_ratio: 0.0216,
      cr_passed: true,
      normalized_criteria: { slope_norm: 1.0, ph_norm: 0.80, rainfall_norm: 0.80, temp_norm: 0.75, land_use_norm: 1.0, irrigation_norm: 0.70, ndvi_norm: 0.75, moisture_norm: 0.75 },
      summary_th: "ค่าความเหมาะสมต่อการเกษตรโดยรวม: 0.79 (S2) — คำนวณตามสูตร AHP Weighted Overlay 8 ปัจจัย S = Σ(wi × xi) (CR = 0.0216 < 0.10)",
    },
    suitability_score: 79,
    status_label: "ปานกลาง",
    status_color: "#B4841F",
    fao_class: "S2",
    fao_label: "เหมาะสมปานกลาง (S2)",
    ndvi_value: 0.65,
    ndvi_trend: [
      { month: "มี.ค.", value: 0.55 },
      { month: "เม.ย.", value: 0.52 },
      { month: "พ.ค.", value: 0.61 },
      { month: "มิ.ย.", value: 0.63 },
      { month: "ก.ค.", value: 0.66 },
      { month: "ส.ค.", value: 0.65 },
    ],
    soil_moisture: 58,
    slope_degrees: 1.2,
    elevation_amsl: 8.5,
    surface_temp: 31.0,
    rainfall_mm: 1100,
    soil_ph: 5.8,
    land_use_class: "Cropland",
    soil_group: THAILAND_SOIL_GROUPS[44],
    insight_text:
      "พื้นที่ราบลุ่ม ดินร่วนปนทรายระบายน้ำเร็ว เหมาะกับพืชไร่เศรษฐกิจที่ทนแล้งปานกลาง เช่น อ้อย มันสำปะหลัง หรือข้าวโพดเลี้ยงสัตว์ แนะนำให้เสริมระบบน้ำหยดเพื่อเพิ่มผลผลิต",
  },
};

export const mockCrops: Crop[] = [
  {
    id: "crop-rice",
    name: "ข้าวหอมมะลิ 105",
    category: "พืชไร่ / ธัญพืช",
    icon_emoji: "🌾",
    image_url: "/crops/rice.jpg",
    fao_class: "S1",
    fao_label: "เหมาะสมมาก (S1)",
    match_percentage: 95,
    growth_duration: "120 - 130 วัน",
    water_requirement: "สูง",
    water_level: 3,
    estimated_yield: "520 - 650 กก./ไร่",
    ideal_temperature_range: "20°C - 35°C",
    best_season: "ฤดูฝน (นาปี: ก.ค. - พ.ย.)",
    soil_preference: "ดินเหนียวหรือดินร่วนเหนียว ที่ราบลุ่มระบายน้ำเลว (กลุ่มชุดดินที่ 1, 2, 3, 7)",
    description: "ข้าวเศรษฐกิจหลักของไทยที่ราคาสูง ต้องการพื้นที่ราบลุ่มอุ้มน้ำได้ดีเพื่อความสมบูรณ์ของรวงข้าว",
    pros: [
      "สอดคล้องกับคุณสมบัติของดินเหนียวลุ่มน้ำเจ้าพระยา (กลุ่มชุดดินที่ 7)",
      "ความลาดชัน 1.8° เหมาะสมกับการขังน้ำข้าวมะลิ",
      "ระดับความชื้นในดิน 68% เพียงพอต่อการสร้างรวงข้าวคุณภาพสูง",
    ],
    cautions: [
      "ควรเฝ้าระวังโรคขอบใบแห้งในช่วงที่มีความชื้นสัมพัทธ์สูง",
      "หลีกเลี่ยงการใช้น้ำบาดาลที่มีค่าความเค็มสูงเกินเกณฑ์",
    ],
  },
];
