

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aurafarm-backend
    restart: always
    environment:
      - PORT=8000
      - EE_PROJECT_ID=aurafarm-507404
      # Paste your Google Service Account JSON string here or mount service_account.json
      # - GEE_SERVICE_ACCOUNT_JSON={"type": "service_account", ...}
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aurafarm-frontend
    restart: always
    environment:
      - NODE_ENV=production
      - PYTHON_BACKEND_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
