"""
Crop Requirement Database for Thailand Economic Crops
อ้างอิง: คู่มือการจำแนกความเหมาะสมของดินสำหรับพืชเศรษฐกิจ กรมพัฒนาที่ดิน (LDD) & FAO EcoCrop Database
"""

from typing import Dict, List, Any

CROP_REQUIREMENTS_DATABASE: Dict[str, Dict[str, Any]] = {
    "rice_jasmine_105": {
        "id": "crop-rice",
        "name": "ข้าวหอมมะลิ 105",
        "category": "พืชไร่ / ธัญพืช",
        "icon_emoji": "🌾",
        "source": "กรมพัฒนาที่ดิน (LDD) & FAO EcoCrop",
        "soil_groups_s1": [1, 2, 3, 7],
        "soil_groups_s2": [11, 24],
        "soil_groups_forbidden": [17, 33, 44, 56],
        "slope_max_deg": 3.0,
        "rainfall_optimal_mm": (1200, 1800),
        "soil_moisture_optimal_pct": (60, 90),
        "temp_optimal_celsius": (25.0, 32.0),
        "elevation_max_m": 350,
        "soil_depth_min_cm": 50,
        "drainage_preference": "poorly_drained"
    },
    "sugarcane_kk3": {
        "id": "crop-sugarcane",
        "name": "อ้อยโรงงาน (ขอนแก่น 3)",
        "category": "พืชไร่ / ธัญพืช",
        "icon_emoji": "🎋",
        "source": "สำนักงานคณะกรรมการอ้อยและน้ำตาลทราย & กรมพัฒนาที่ดิน",
        "soil_groups_s1": [29, 33, 44],
        "soil_groups_s2": [38, 48],
        "soil_groups_forbidden": [1, 2, 11],
        "slope_max_deg": 6.0,
        "rainfall_optimal_mm": (1000, 1500),
        "soil_moisture_optimal_pct": (45, 70),
        "temp_optimal_celsius": (28.0, 35.0),
        "elevation_max_m": 450,
        "soil_depth_min_cm": 80,
        "drainage_preference": "well_drained"
    },
    "cassava_rayong_72": {
        "id": "crop-cassava",
        "name": "มันสำปะหลัง (ระยอง 72)",
        "category": "พืชไร่ / ธัญพืช",
        "icon_emoji": "🥔",
        "source": "สถาบันพัฒนามันสำปะหลังแห่งประเทศไทย & กรมวิชาการเกษตร",
        "soil_groups_s1": [33, 44, 17],
        "soil_groups_s2": [29, 38],
        "soil_groups_forbidden": [1, 2, 7, 11],
        "slope_max_deg": 8.0,
        "rainfall_optimal_mm": (800, 1400),
        "soil_moisture_optimal_pct": (30, 60),
        "temp_optimal_celsius": (25.0, 34.0),
        "elevation_max_m": 600,
        "soil_depth_min_cm": 60,
        "drainage_preference": "well_drained"
    },
    "durian_monthong": {
        "id": "crop-durian",
        "name": "ทุเรียนหมอนทอง",
        "category": "ไม้ผลเศรษฐกิจ",
        "icon_emoji": "🍈",
        "source": "กรมวิชาการเกษตร (GAP) & กรมพัฒนาที่ดิน",
        "soil_groups_s1": [48, 29, 38],
        "soil_groups_s2": [33, 44],
        "soil_groups_forbidden": [1, 2, 7, 11, 17],
        "slope_min_deg": 1.5,
        "slope_max_deg": 12.0,
        "rainfall_optimal_mm": (1800, 2800),
        "soil_moisture_optimal_pct": (60, 80),
        "temp_optimal_celsius": (24.0, 32.0),
        "elevation_max_m": 650,
        "soil_depth_min_cm": 100,
        "drainage_preference": "well_drained"
    },
    "rubber_rrim600": {
        "id": "crop-rubber",
        "name": "ยางพารา (RRIM 600)",
        "category": "ไม้ยืนต้น / อุตสาหกรรม",
        "icon_emoji": "🪵",
        "source": "การยางแห่งประเทศไทย (กยท.) & กรมพัฒนาที่ดิน",
        "soil_groups_s1": [38, 48, 29],
        "soil_groups_s2": [44, 56],
        "soil_groups_forbidden": [1, 2, 7, 11, 17],
        "slope_max_deg": 15.0,
        "rainfall_optimal_mm": (1600, 3000),
        "soil_moisture_optimal_pct": (65, 85),
        "temp_optimal_celsius": (25.0, 33.0),
        "elevation_max_m": 600,
        "soil_depth_min_cm": 100,
        "drainage_preference": "well_drained"
    },
    "oilpalm_tenera": {
        "id": "crop-oilpalm",
        "name": "ปาล์มน้ำมัน (เทเนอรา)",
        "category": "ไม้ยืนต้น / อุตสาหกรรม",
        "icon_emoji": "🌴",
        "source": "สมาคมโรงงานสกัดน้ำมันปาล์ม & กรมวิชาการเกษตร",
        "soil_groups_s1": [2, 7, 48],
        "soil_groups_s2": [29, 38],
        "soil_groups_forbidden": [11, 17, 56],
        "slope_max_deg": 6.0,
        "rainfall_optimal_mm": (2000, 3500),
        "soil_moisture_optimal_pct": (70, 90),
        "temp_optimal_celsius": (26.0, 34.0),
        "elevation_max_m": 300,
        "soil_depth_min_cm": 100,
        "drainage_preference": "moderately_well_drained"
    },
    "coffee_arabica": {
        "id": "crop-coffee-arabica",
        "name": "กาแฟอาราบิก้า",
        "category": "ไม้ยืนต้น / อุตสาหกรรม",
        "icon_emoji": "☕",
        "source": "สถาบันวิจัยและพัฒนาพื้นที่สูง (สวพส.)",
        "soil_groups_s1": [56, 48],
        "soil_groups_s2": [38],
        "soil_groups_forbidden": [1, 2, 7, 11, 17],
        "slope_max_deg": 18.0,
        "rainfall_optimal_mm": (1400, 2200),
        "soil_moisture_optimal_pct": (60, 80),
        "temp_optimal_celsius": (15.0, 25.0),
        "elevation_min_m": 750,
        "elevation_max_m": 1600,
        "soil_depth_min_cm": 80,
        "drainage_preference": "well_drained"
    }
}
